version: "3"
services:
  traefik:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
      restart_policy:
        condition: on-failure
    image: traefik:1.5.4
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json

  nginx:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=nginx
        - traefik.domain=cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:cameras.puppywood.com
        - traefik.port=80
        - traefik.protocol=http
    image: library/nginx
    networks:
      - web
    volumes:
      - /opt/nginx/index.html:/usr/share/nginx/html/index.html
      - /opt/nginx/montgomery-cams.html:/usr/share/nginx/html/montgomery-cams.html
      - /opt/nginx/beechmont-cams.html:/usr/share/nginx/html/beechmont-cams.html
      - /opt/nginx/:/opt/www

  # webrtc-streamer-all:
  #   command: -C config.json
  #   deploy:
  #     replicas: 1
  #     update_config:
  #       parallelism: 1
  #       delay: 10s
  #     restart_policy:
  #       condition: on-failure
  #     labels:
  #       - traefik.docker.network=web
  #       - traefik.backend=webrtc-streamer
  #       - traefik.domain=cameras.puppywood.com
  #       - traefik.enable=true
  #       - traefik.frontend.rule=Host:cameras.puppywood.com
  #       - traefik.port=8000
  #       - traefik.protocol=http
  #   image: mpromonet/webrtc-streamer
  #   networks:
  #     - web
  #   volumes:
  #     - /opt/webrtc-streamer/config.json:/app/config.json

  # webrtc-streamer-montgomery:
  #   command: -C config.json
  #   deploy:
  #     replicas: 1
  #     update_config:
  #       parallelism: 1
  #       delay: 10s
  #     restart_policy:
  #       condition: on-failure
  #     labels:
  #       - traefik.docker.network=web
  #       - traefik.backend=webrtc-streamer-montgomery
  #       - traefik.domain=montgomery.cameras.puppywood.com
  #       - traefik.enable=true
  #       - traefik.frontend.rule=Host:montgomery.cameras.puppywood.com
  #       - traefik.port=8000
  #       - traefik.protocol=http
  #   image: mpromonet/webrtc-streamer
  #   networks:
  #     - web
  #   volumes:
  #     - /opt/webrtc-streamer/config-montgomery.json:/app/config.json

  webrtc-streamer-beechmont:
    command: -C config.json
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=webrtc-streamer-beechmont
        - traefik.domain=beechmont.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:beechmont.cameras.puppywood.com
        - traefik.port=8000
        - traefik.protocol=http
    image: mpromonet/webrtc-streamer
    networks:
      - web
    volumes:
      - /opt/webrtc-streamer/config-beechmont.json:/app/config.json

  mjpeg-montgomery1:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=mjpeg-montgomery1
        - traefik.domain=montgomery1.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:montgomery1.cameras.puppywood.com
        - traefik.port=8081
        - traefik.protocol=http
    environment:
      MJPEG_URL: "http://cameras1.puppywood.com/axis-cgi/mjpg/video.cgi?resolution=4CIF&camera=1"
    image: roflmao/docker-mjpeg-proxy
    networks:
      - web

  mjpeg-montgomery2:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=mjpeg-montgomery2
        - traefik.domain=montgomery2.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:montgomery2.cameras.puppywood.com
        - traefik.port=8081
        - traefik.protocol=http
    environment:
      MJPEG_URL: "http://cameras1.puppywood.com/axis-cgi/mjpg/video.cgi?resolution=4CIF&camera=2"
    image: roflmao/docker-mjpeg-proxy
    networks:
      - web

  mjpeg-montgomery3:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=mjpeg-montgomery3
        - traefik.domain=montgomery3.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:montgomery3.cameras.puppywood.com
        - traefik.port=8081
        - traefik.protocol=http
    environment:
      MJPEG_URL: "http://cameras1.puppywood.com/axis-cgi/mjpg/video.cgi?resolution=4CIF&camera=3"
    image: roflmao/docker-mjpeg-proxy
    networks:
      - web

  mjpeg-montgomery4:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=mjpeg-montgomery4
        - traefik.domain=montgomery4.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:montgomery4.cameras.puppywood.com
        - traefik.port=8081
        - traefik.protocol=http
    environment:
      MJPEG_URL: "http://cameras1.puppywood.com/axis-cgi/mjpg/video.cgi?resolution=4CIF&camera=4"
    image: roflmao/docker-mjpeg-proxy
    networks:
      - web

  # mjpeg-montgomery-quad-1-4:
  #   deploy:
  #     replicas: 1
  #     update_config:
  #       parallelism: 1
  #       delay: 10s
  #     restart_policy:
  #       condition: on-failure
  #     labels:
  #       - traefik.docker.network=web
  #       - traefik.backend=mjpeg-montgomery-quad-1-4
  #       - traefik.domain=montgomery-quad-1-4.cameras.puppywood.com
  #       - traefik.enable=true
  #       - traefik.frontend.rule=Host:montgomery-quad-1-4.cameras.puppywood.com
  #       - traefik.port=8081
  #       - traefik.protocol=http
  #   environment:
  #     MJPEG_URL: "http://cameras1.puppywood.com/axis-cgi/mjpg/video.cgi?resolution=4CIF&camera=quad"
  #   image: roflmao/docker-mjpeg-proxy
  #   networks:
  #     - web

  mjpeg-montgomery5:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=mjpeg-montgomery5
        - traefik.domain=montgomery5.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:montgomery5.cameras.puppywood.com
        - traefik.port=8081
        - traefik.protocol=http
    environment:
      MJPEG_URL: "http://cameras1.puppywood.com:81/axis-cgi/mjpg/video.cgi?resolution=4CIF&camera=1"
    image: roflmao/docker-mjpeg-proxy
    networks:
      - web

  mjpeg-montgomery6:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=mjpeg-montgomery6
        - traefik.domain=montgomery6.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:montgomery6.cameras.puppywood.com
        - traefik.port=8081
        - traefik.protocol=http
    environment:
      MJPEG_URL: "http://cameras1.puppywood.com:81/axis-cgi/mjpg/video.cgi?resolution=4CIF&camera=2"
    image: roflmao/docker-mjpeg-proxy
    networks:
      - web

  mjpeg-montgomery7:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=mjpeg-montgomery7
        - traefik.domain=montgomery7.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:montgomery7.cameras.puppywood.com
        - traefik.port=8081
        - traefik.protocol=http
    environment:
      MJPEG_URL: "http://cameras1.puppywood.com:81/axis-cgi/mjpg/video.cgi?resolution=4CIF&camera=3"
    image: roflmao/docker-mjpeg-proxy
    networks:
      - web

  mjpeg-montgomery8:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=mjpeg-montgomery8
        - traefik.domain=montgomery8.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:montgomery8.cameras.puppywood.com
        - traefik.port=8081
        - traefik.protocol=http
    environment:
      MJPEG_URL: "http://cameras1.puppywood.com:81/axis-cgi/mjpg/video.cgi?resolution=4CIF&camera=4"
    image: roflmao/docker-mjpeg-proxy
    networks:
      - web

  # mjpeg-montgomery-quad-5-8:
  #   deploy:
  #     replicas: 1
  #     update_config:
  #       parallelism: 1
  #       delay: 10s
  #     restart_policy:
  #       condition: on-failure
  #     labels:
  #       - traefik.docker.network=web
  #       - traefik.backend=mjpeg-montgomery-quad-5-8
  #       - traefik.domain=montgomery-quad-5-8.cameras.puppywood.com
  #       - traefik.enable=true
  #       - traefik.frontend.rule=Host:montgomery-quad-5-8.cameras.puppywood.com
  #       - traefik.port=8081
  #       - traefik.protocol=http
  #   environment:
  #     MJPEG_URL: "http://cameras1.puppywood.com:81/axis-cgi/mjpg/video.cgi?resolution=4CIF&camera=quad"
  #   image: roflmao/docker-mjpeg-proxy
  #   networks:
  #     - web

networks:
  web:
    external: true
