version: "3"
services:
  traefik:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 3s
      restart_policy:
        condition: on-failure
    image: traefik:1.5.4
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json

  nginx:
    # command:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=nginx
        - traefik.domain=cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:cameras.puppywood.com
        - traefik.port=80
        - traefik.protocol=http
    image: library/nginx
    networks:
      - web
    volumes:
      - /opt/nginx/index.html:/usr/share/nginx/html/index.html
      - /opt/nginx/:/opt/www

  # webrtc-streamer-all:
  #   command: -C config.json
  #   deploy:
  #     replicas: 1
  #     update_config:
  #       parallelism: 1
  #       delay: 10s
  #     restart_policy:
  #       condition: on-failure
  #     labels:
  #       - traefik.docker.network=web
  #       - traefik.backend=webrtc-streamer
  #       - traefik.domain=cameras.puppywood.com
  #       - traefik.enable=true
  #       - traefik.frontend.rule=Host:cameras.puppywood.com
  #       - traefik.port=8000
  #       - traefik.protocol=http
  #   image: mpromonet/webrtc-streamer
  #   networks:
  #     - web
  #   volumes:
  #     - /opt/webrtc-streamer/config.json:/app/config.json

  webrtc-streamer-montgomery:
    command: -C config.json
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=webrtc-streamer-montgomery
        - traefik.domain=montgomery.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:montgomery.cameras.puppywood.com
        - traefik.port=8000
        - traefik.protocol=http
    image: mpromonet/webrtc-streamer
    networks:
      - web
    volumes:
      - /opt/webrtc-streamer/config-montgomery.json:/app/config.json

  webrtc-streamer-beechmont:
    command: -C config.json
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=webrtc-streamer-beechmont
        - traefik.domain=beechmont.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:beechmont.cameras.puppywood.com
        - traefik.port=8000
        - traefik.protocol=http
    image: mpromonet/webrtc-streamer
    networks:
      - web
    volumes:
      - /opt/webrtc-streamer/config-beechmont.json:/app/config.json

  mjpeg-montgomery1:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=mjpeg-montgomery1
        - traefik.domain=montgomery.cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:montgomery1.cameras.puppywood.com
        - traefik.port=8081
        - traefik.protocol=http
    environment:
      MJPEG_URL: "http://cameras1.puppywood.com/axis-cgi/mjpg/video.cgi?resolution=4CIF&camera=1"
    image: roflmao/docker-mjpeg-proxy
    networks:
      - web

networks:
  web:
    external: true
