version: "3"
services:
  webrtc-streamer:
    command: -C config.json
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        - traefik.docker.network=web
        - traefik.backend=webrtc-streamer
        - traefik.domain=cameras.puppywood.com
        - traefik.enable=true
        - traefik.frontend.rule=Host:cameras.puppywood.com
        - traefik.port=8000
        - traefik.protocol=http
    image: mpromonet/webrtc-streamer
    networks:
      - web
    volumes:
      - /opt/webrtc-streamer/config.json:/app/config.json

  traefik:
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
    image: traefik:1.5.4
    ports:
      - 80:80
      - 443:443
    networks:
      - web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/traefik.toml:/traefik.toml
      - /opt/traefik/acme.json:/acme.json

networks:
  web:
    external: true
