debug = false

logLevel = "INFO"
defaultEntryPoints = ["https","http"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  [entryPoints.https.tls]

[retry]

[docker]
swarmMode = true
endpoint = "unix:///var/run/docker.sock"
domain = "cameras.puppywood.com"
watch = true
exposedbydefault = true

[acme]
email = "me@cameras.puppywood.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[[acme.domains]]
  main = "cameras.puppywood.com"
  sans = ["beechmont.cameras.puppywood.com", "montgomery.cameras.puppywood.com", "montgomery1.cameras.puppywood.com", "montgomery2.cameras.puppywood.com", "montgomery3.cameras.puppywood.com", "montgomery4.cameras.puppywood.com", "montgomery5.cameras.puppywood.com", "montgomery6.cameras.puppywood.com", "montgomery7.cameras.puppywood.com", "montgomery9.cameras.puppywood.com" ]